commit

diff --git a/.github/workflows/workflow.yml b/.github/workflows/workflow.yml
--- a/.github/workflows/workflow.yml
+++ b/.github/workflows/workflow.yml
@@ -12,8 +12,13 @@ jobs:
     steps:
       - uses: actions/checkout@v3
       - run: |
-          scripts/foo.sh;
-          echo "export TEST_RESULT=$?" >> $GITHUB_ENV
+          if scripts/foo.sh; then
+            echo "export TEST_RESULT=$?" >> $GITHUB_ENV
+            echo "::info ::Test success"
+          else
+            echo "export TEST_RESULT=$?" >> $GITHUB_ENV
+            echo "::error ::Test failed"
+          fi
           exit ${TEST_RESULT}
       - run: echo "Printing line after script execution on failure"
         name: "execute on failure"
