commit

diff --git a/.github/workflows/workflow.yml b/.github/workflows/workflow.yml
--- a/.github/workflows/workflow.yml
+++ b/.github/workflows/workflow.yml
@@ -11,7 +11,14 @@ jobs:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v3
-      - run: ./scripts/foo.sh
+      - run: |
+        if ./scripts/foo.sh; then
+          echo "::notice ::Test success"
+          echo "export TEST_RESULT=$?" >> $GITHUB_ENV
+        else
+          echo "::notice ::Test failed"
+          echo "export TEST_RESULT=$?" >> $GITHUB_ENV
+        fi
       - run: echo "Printing line after script execution on failure"
         if: failure()
       - run: echo "final step"
